# This file was generated by GoReleaser. DO NOT EDIT.
cask "paymostats" do
  name "Paymostats"

  desc "Small CLI tool to display Paymo stats within a given range"
  homepage "https://github.com/Ma-Kas/paymostats"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "paymostats"

  on_macos do
    on_intel do
      url "https://github.com/Ma-Kas/paymostats/releases/download/v0.1.1/paymostats_0.1.1_darwin_amd64.tar.gz"
      sha256 "ada0dfa69ece249e2d9b862bf518b679748c8f8d7feae1c03be791a6fe9e638c"
    end
    on_arm do
      url "https://github.com/Ma-Kas/paymostats/releases/download/v0.1.1/paymostats_0.1.1_darwin_arm64.tar.gz"
      sha256 "e9c21fb08cc3bdeb042fd595d9892b180c86e5e9cb3d2f2565396ecb11d29423"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Ma-Kas/paymostats/releases/download/v0.1.1/paymostats_0.1.1_linux_amd64.tar.gz"
      sha256 "08aba2f0ab3ead6c6b2af132328aa01c90da7f7c93408cd1d34010d076c01d66"
    end
    on_arm do
      url "https://github.com/Ma-Kas/paymostats/releases/download/v0.1.1/paymostats_0.1.1_linux_arm64.tar.gz"
      sha256 "d1a183cd1993f7bdb7586951175631ef8eb12e6fa8a099865be5176437b0449c"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/paymostats"]
    end
  end

  # No zap stanza required
end
