# This file was generated by GoReleaser. DO NOT EDIT.
cask "paymostats" do
  desc "Small CLI tool to display Paymo stats within a given range"
  homepage "https://github.com/Ma-Kas/paymostats"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "paymostats"

  on_macos do
    on_intel do
      url "https://github.com/Ma-Kas/paymostats/releases/download/v0.1.0/paymostats_0.1.0_darwin_amd64.tar.gz"
      sha256 "7fe2f56a3c70e809c12e6840ee80afcf276aea4e8050d144057e1f88e91a9cb1"
    end
    on_arm do
      url "https://github.com/Ma-Kas/paymostats/releases/download/v0.1.0/paymostats_0.1.0_darwin_arm64.tar.gz"
      sha256 "0d263bf7b3082b29a9577ede03d3c3dc6ea3477b55b7177564c30596443bcb9b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Ma-Kas/paymostats/releases/download/v0.1.0/paymostats_0.1.0_linux_amd64.tar.gz"
      sha256 "496f0e5304afbcaa30605ecdcfeb584581e6f19d6441950b797aa7a8f0b046cc"
    end
    on_arm do
      url "https://github.com/Ma-Kas/paymostats/releases/download/v0.1.0/paymostats_0.1.0_linux_arm64.tar.gz"
      sha256 "4a6958bd1c2d3160b9594f7a50ae78c2846cb8d8d4b6515ba516bf2e85a9f464"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/paymostats"]
    end
  end

  # No zap stanza required
end
